sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table address --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.address --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table addresstype --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.addresstype --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table awbuildversion --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.awbuildversion --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table billofmaterials --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.billofmaterials --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table contact --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.contact --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table contactcreditcard --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.contactcreditcard --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table contacttype --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.contacttype --hive-overwrite
sqoop import -Dorg.apache.sqoop.splitter.allow_text_splitter=true --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table countryregion --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.countryregion --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table creditcard --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.creditcard --hive-overwrite
sqoop import -Dorg.apache.sqoop.splitter.allow_text_splitter=true --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table culture --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.culture --hive-overwrite
sqoop import -Dorg.apache.sqoop.splitter.allow_text_splitter=true --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table currency --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.currency --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table currencyrate --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.currencyrate --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table customer --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.customer --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table customeraddress --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.customeraddress --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table databaselog --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.databaselog --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table department --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.department --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table employee --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.employee --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table employeeaddress --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.employeeaddress --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table employeedepartmenthistory --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.employeedepartmenthistory --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table employeepayhistory --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.employeepayhistory --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table errorlog --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.errorlog --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table illustration --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.illustration --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table individual --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.individual --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table jobcandidate --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.jobcandidate --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table location --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.location --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table product --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.product --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productcategory --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productcategory --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productcosthistory --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productcosthistory --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productdescription --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productdescription --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productdocument --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productdocument --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productinventory --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productinventory --hive-overwrite -map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productlistpricehistory --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productlistpricehistory --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productmodel --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productmodel --hive-overwrite -map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productmodelillustration --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productmodelillustration --hive-overwrite
sqoop import -Dorg.apache.sqoop.splitter.allow_text_splitter=true --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productmodelproductdescriptionculture --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productmodelproductdescriptionculture --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productproductphoto --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productproductphoto --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productreview --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productreview --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productsubcategory --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productsubcategory --hive-overwrite -map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table productvendor --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.productvendor --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table purchaseorderdetail --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.purchaseorderdetail --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table purchaseorderheader --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.purchaseorderheader --hive-overwrite --split-by PurchaseOrderID
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table salesorderdetail --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.salesorderdetail --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table salesorderheader --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.salesorderheader --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table salesorderheadersalesreason --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.salesorderheadersalesreason --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table salesperson --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.salesperson --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table salespersonquotahistory --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.salespersonquotahistory --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table salesreason --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.salesreason --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table salestaxrate --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.salestaxrate --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table salesterritory --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.salesterritory --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table salesterritoryhistory --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.salesterritoryhistory --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table scrapreason --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.scrapreason --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table shift --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.shift --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table shipmethod --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.shipmethod --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table shoppingcartitem --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.shoppingcartitem --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table specialoffer --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.specialoffer --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table specialofferproduct --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.specialofferproduct --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table stateprovince --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.stateprovince --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table store --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.store --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table storecontact --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.storecontact --hive-overwrite --map-column-hive rowguid=binary
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table transactionhistory --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.transactionhistory --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table transactionhistoryarchive --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.transactionhistoryarchive --hive-overwrite
sqoop import -Dorg.apache.sqoop.splitter.allow_text_splitter=true --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table unitmeasure --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.unitmeasure --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table vendor --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.vendor --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table vendoraddress --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.vendoraddress --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table vendorcontact --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.vendorcontact --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table workorder --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.workorder --hive-overwrite
sqoop import --connect jdbc:mysql://localhost:3306/adventureworks?serverTimezone=UTC --table workorderrouting --username root --password Dsahadoop@1 --hive-import --hive-table temp_adventureworks.workorderrouting --hive-overwrite












